### ISSUE TITLE
How about the pic

### ISSUE THREAD

**Issue by TerenceLiu98** [tchapeaux/info-f413-secretary-problem#1]
Hi, I just want to ask when you will add the graph

**Comment by tchapeaux** [comment]
Hi !

This was a school project from 6 years ago, but maybe I can still help.

Which graph are you referring to? The only graph in the report is in the repo already: https://github.com/tchapeaux/info-f413-secretary-problem/blob/master/success_m_graph.png

**Comment by tchapeaux** [comment]
Ok, I guess you're talking about the missing graph from section 2.2 "Calcul de la somme"

Lucky for you, I still have it in my archives, you can find it here:
https://photos.app.goo.gl/C1brW0cD7P7CrPOk2
(yes, as you can see I was too lazy to draw it properly... 😄 )

Does that help?

**Comment by TerenceLiu98** [comment]
haha😄!  This is my school project now! Thanks for your code and your helping! 
I thought you won't reply this issues since it is a 6 years old repo, how lucky! I cloned this repo into my repo: https://github.com/TerenceLiu98/MATH-MODELLING, maybe some days later I will rewrite it in Python 3

**Comment by tchapeaux** [comment]
No problem, good luck on your school project
